server:
  port: 80

spring:
  application:
    name: microservicecloud-consumer                            #对外暴露的服务的名字
  devtools:
    restart:
      enabled: false
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/   #集群
  instance:
    instance-id: microservicecloud-consumer80
    prefer-ip-address: true     #访问路径可以显示IP地址
